### ISSUE TITLE
20news.json

### ISSUE THREAD

**Issue by Charles1757** [slei109/TART#2]
Hi, sorry for bothering, would you mind sharing this "../data/20news.json"?

**Comment by slei109** [comment]
You can find the download link from Data description in README.md.

**Comment by Charles1757** [comment]
sorry, still not find the data.zip which you mentioned in README.md

**Comment by Charles1757** [comment]
> You can find the download link from Data description in README.md.
sorry, still not find the data.zip which you mentioned in README.md
